### ISSUE TITLE
The output file '*.Locations' for the script 'LocateSSRsandORFs.py' is very confusing

### ISSUE THREAD

**Issue by guetsane** [soltislab/transcriptome_microsats#1]
There seems to be an issue with the output '*.Locations' of the script 'LocateSSRsandORFs.py'. This output is supposed to summarize the locations of SSRs relative to the longest ORF on EACH scaffold. Instead, for EVERY SSR identified, the output shows the name of the LAST scaffold|ORF number in the first column; and in the sixth and seventh columns, respectively, the start and the end of the longest ORF on the last scaffold.

**Comment by magitz** [comment]
Hi,
Thanks for the bug report. I believe I have fixed this now. The issue should not have effected the results of the paper as I didn't use the .Locations file, just the summary file which had things calculated correctly.

Please let me know if you have other issues.
Thanks,
Matt

**Comment by guetsane** [comment]
Thank you for your prompt response.

Atibalentja

On Thu, Jun 9, 2016 at 10:24 AM, Matt Gitzendanner <notifications@github.com
