### ISSUE TITLE
getting Error while running LocateSSRsandORFs.py

### ISSUE THREAD

**Issue by Ravindra-Raut** [soltislab/transcriptome_microsats#2]
CAMMAND:
python ./LocateSSRsandORFs.py -i Pterocarpus_rohrii.ORFS.faa -r Pterocarpus_rohrii.fna.misa_SSR.results -o Pterocarpus_rohrii.Locations -s SSR_ORF_summary.txt

OUTPUT:
File "LocateSSRsandORFs.py", line 40
    print "Can't open file", resultfile
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Can't open file", resultfile)?

I am getting this error, can anyone help with this?

**Comment by magitz** [comment]
These scripts were written under python2. My guess is that all you will need to do to make them python3 compatible is put the print statements in parentheses. I will put this on a to do list to update the scripts for python3 compatibility.
Thanks for the report.
Matt

**Comment by Ravindra-Raut** [comment]
thanks for reply

**Comment by magitz** [comment]
This has been fixed. Thanks and hope you were able to get this working before now on your own.
